---
title: "Genomic Data Site Characteristics"
author: "Alex Baras"
date: "`r Sys.Date()`"
output: html_document
---


```{r, echo=FALSE}

# libraries
library(synapseClient)
library(knitr)
library(lattice)

# login to SAGE
synapseLogin(username="",password="") # you could do this with prompt or coded, but will need to enter something here

# read aggregated MAF file
genieMutData = read.delim(synGet("syn5571527")@filePath,header=TRUE,sep="\t",quote="",comment="",skip = 1)

# records with count data that preclude a VAF estimate - set VAF to 100% (1/1, alt/depth)
noVAF.idx = which((genieMutData$t_depth==0)|is.na(genieMutData$t_depth))
genieMutData$t_alt_count_num = as.numeric(levels(genieMutData$t_alt_count))[genieMutData$t_alt_count]
genieMutData$t_alt_count_num[noVAF.idx] = 1
genieMutData$t_depth[noVAF.idx] = 1

```

### SUB vs INS vs DEL

```{r, echo=FALSE}

# SUB vs INS/DEL TABLE
t = as.data.frame.matrix(table(genieMutData$Center,genieMutData$Variant_Type))
t = as.data.frame(cbind(rowSums(t[,c("SNP","DNP","TNP","ONP")]),t[,"INS"],t[,"DEL"]))
colnames(t) = c("SUB","INS","DEL")
t = data.frame(n=rowSums(t),t)
t[,colnames(t)!="n"] = t[,colnames(t)!="n"]/rowSums(t[,colnames(t)!="n"])
kable(t[order(t$SUB),],digits=3)

# SUB vs INS/DEL BARCHARTS
t$Center = rownames(t)
t = reshape(t,direction="long",idvar=("Center"),varying=c("SUB","INS","DEL"),v.names="Percentage",times=c("SUB","INS","DEL"))
colnames(t)[colnames(t)=="time"] = "Type"
t$Type = factor(t$Type,c("SUB","INS","DEL"))
barchart( t$Percentage ~ t$Type | t$Center,ylim=c(0,1))

```

### SUB Length

```{r, echo=FALSE}

# SUB TABLES
k = which((genieMutData$Reference_Allele!="-") & (genieMutData$Tumor_Seq_Allele2!="-") & (nchar(as.character(genieMutData$Reference_Allele))==nchar(as.character(genieMutData$Tumor_Seq_Allele2))))
t = as.data.frame.matrix(table(genieMutData$Center[k],nchar(as.character(genieMutData$Reference_Allele[k]))))
t = data.frame(n=rowSums(t),t)
colnames(t) = sub("X","",colnames(t))
t[,colnames(t)!="n"] = t[,colnames(t)!="n"]/rowSums(t[,colnames(t)!="n"])
kable(t[order(t[,2]),],digits=3)

# SUB HISTOGRAMS
histogram(~nchar(as.character(genieMutData$Tumor_Seq_Allele2[k]))|genieMutData$Center[k],breaks=c(0.5:20.5,30,40),xlim=c(0,10),ftype="percent",right=FALSE)

```

### INS Length

```{r, echo=FALSE}

# INS TABLE
k = which((genieMutData$Reference_Allele=="-") | (nchar(as.character(genieMutData$Reference_Allele))<nchar(as.character(genieMutData$Tumor_Seq_Allele2))))
t = as.data.frame.matrix(table(genieMutData$Center[k],nchar(as.character(genieMutData$Tumor_Seq_Allele2[k]))))
t = data.frame(n=rowSums(t),t)
colnames(t) = sub("X","",colnames(t))
t[,colnames(t)!="n"] = t[,colnames(t)!="n"]/rowSums(t[,colnames(t)!="n"])
kable(t[order(t[,2]),],digits=3)

# INS HISTOGRAMS
histogram(~nchar(as.character(genieMutData$Tumor_Seq_Allele2[k]))|genieMutData$Center[k],ftype="percent",breaks=c(0.5:20.5,30,40,50,100,200),xlim=c(0,20),right=TRUE)

```

### DEL Length

```{r, echo=FALSE}

# DEL TABLE
k = which((genieMutData$Tumor_Seq_Allele2=="-") | (nchar(as.character(genieMutData$Reference_Allele))>nchar(as.character(genieMutData$Tumor_Seq_Allele2))))
t = as.data.frame.matrix(table(genieMutData$Center[k],nchar(as.character(genieMutData$Reference_Allele[k]))))
t = data.frame(n=rowSums(t),t)
colnames(t) = sub("X","",colnames(t))
t[,colnames(t)!="n"] = t[,colnames(t)!="n"]/rowSums(t[,colnames(t)!="n"])
kable(t[order(t[,2]),],digits=3)

# DEL HISTOGRAMS
histogram(~nchar(as.character(genieMutData$Tumor_Seq_Allele2[k]))|genieMutData$Center[k],ftype="percent",breaks=c(0.5:20.5,30,40,50,100,200),xlim=c(0,20),right=TRUE)

```

### SNV type

```{r, echo=FALSE}

# SNV type breakdown TABLE
t = as.data.frame.matrix(table(genieMutData$Center[genieMutData$Variant_Type=="SNP"],paste(genieMutData$Reference_Allele[genieMutData$Variant_Type=="SNP"],".",genieMutData$Tumor_Seq_Allele2[genieMutData$Variant_Type=="SNP"])))
t = data.frame(n=rowSums(t),t)
colnames(t)[2:13] = sub("\\.\\.\\."," -> ",colnames(t)[2:13])
t[,colnames(t)!="n"] = t[,colnames(t)!="n"]/rowSums(t[,colnames(t)!="n"])
kable(t,digits=3)

# SNV type breakdown BARCHARTS
t$Center = rownames(t)
t = reshape(t,direction="long",idvar=("Center"),varying=colnames(t)[2:13],v.names="Percentage",times=colnames(t)[2:13],drop="n")
colnames(t)[colnames(t)=="time"] = "Type"
barchart( t$Type ~ t$Percentage | t$Center,xlim=c(0,0.4))

```

### VAF distribution for SUBs

```{r, echo=FALSE}

k = which(!((genieMutData$Variant_Type=="INS")|(genieMutData$Variant_Type=="DEL")))
histogram(~genieMutData$t_alt_count_num[k]/genieMutData$t_depth[k]|genieMutData$Center[k],ftype="percent",breaks=seq(0,1,0.02),right=FALSE)

```

### VAF distribution for INS/DEL

```{r, echo=FALSE}

k = which(((genieMutData$Variant_Type=="INS")|(genieMutData$Variant_Type=="DEL")))
histogram(~(genieMutData$t_alt_count_num[k]/genieMutData$t_depth[k])|genieMutData$Center[k],ftype="percent",breaks=seq(0,1,0.02),right=FALSE)

```
